export default {
    "users": [
        {
            "id": '61a8a24a-3f30-4f4b-ba1e-68474f25a4d1',
            "email": "sample@fake-email.com",
            "phone": 123-456-7890,
            "username": "pjfry2000",
            "password": "$walkingonsunshine123$",
        },
        {
            "id": '51230acf-f502-4cd0-812b-e4dd59b04cb1',
            "email": "sample2@fake-email.com",
            "phone": null,
            "username": "bart_man",
            "password": "@d0thebartman@",
        },
        {
            "id": 'fccf7cab-93e7-4b1b-ae26-a1f6e24f1b6d',
            "email": "sample3@fake-email.com",
            "phone": 987-654-3210,
            "username": "theAhnold",
            "password": "!HeyArn0ld!",
        },
    ],
    "dog_profiles": [
        {
            "id": 'f3586d96-54fc-43bc-9cff-3564ad317ad6',
            "owner_id": '61a8a24a-3f30-4f4b-ba1e-68474f25a4d1',
            "name": "Seymour",
            "profile_img_url": "https://images.unsplash.com/photo-1580579674179-931317ab63fc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
            "age_years": 15,
            "age_months": 0,
            "sex": "male, unneutered",
            "breed": "mixed-Schnauzer",
            "weight": 20,
            "energy": "About as energetic as the average dog.",
            "temperment": "Outgoing and eager to be friends with most dogs.",
            "obedience": "Some training, but not always obedient.",
            "dislikes_puppies": false,
            "dislikes_men": false,
            "dislikes_women": false,
            "dislikes_children": false,
            "recently_adopted": true,
            "prefers_people": true,
            "leash_aggression": false,
            "elderly_dog": true,
            "little_time_with_other_dogs": false,
            "much_experience_with_other_dogs": true,
            "aggressive": false,
            "owner_description": "Seymour is a sweet dog who loves walking on sunshine, swimming, and eating meatballs.  He enjoys playing with other dogs, though he enjoys smaller dogs more than older ones.  If you see us in Central Park, come say hi!"
        },
        {
            "id": '777e047b-de08-43d7-aa08-a998b4a8430e',
            "owner_id": '61a8a24a-3f30-4f4b-ba1e-68474f25a4d1',
            "name": "Nibbler",
            "profile_img_url": "https://images.unsplash.com/photo-1572297448250-ac6dcaedf2a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1188&q=80",
            "age_years": 5,
            "age_months": 0,
            "sex": "male, unneutered",
            "breed": "Boston Terrier",
            "weight": 25,
            "energy": "Very energetic.",
            "temperment": "Shy, but not skiddish or nervous.",
            "obedience": "Not trained at all and struggles with obedience...",
            "dislikes_puppies": false,
            "dislikes_men": false,
            "dislikes_women": false,
            "dislikes_children": false,
            "recently_adopted": true,
            "prefers_people": true,
            "leash_aggression": false,
            "elderly_dog": false,
            "little_time_with_other_dogs": true,
            "much_experience_with_other_dogs": false,
            "aggressive": true,
            "owner_description": "I recently adopted Nibbler after I found him in the wild on a work trip.  He isn't trained yet, but he's very sweet around people, once he gets to know them.  He's a bit shy around other dogs, very protective of his food, and I suspect that he needs to be socialized.  If your dog is an expert in bringing other dogs out of their shells, send me an email!"
        },
        {
            "id": '1eb7a4e4-ab97-4225-b764-12f72b659971',
            "owner_id": '51230acf-f502-4cd0-812b-e4dd59b04cb1',
            "name": "Santos L. Halper",
            "profile_img_url": "https://images.unsplash.com/photo-1483434748604-140edba26886?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=926&q=80",
            "age_years": 8,
            "age_months": 0,
            "sex": "male, unneutered",
            "breed": "Greyhound",
            "weight": 35,
            "energy": "So...much...energy...it never runs out.",
            "temperment": "Outgoing and eager to be friends with most dogs",
            "obedience": "Some training, but not always obedient.",
            "dislikes_puppies": false,
            "dislikes_men": false,
            "dislikes_women": false,
            "dislikes_children": false,
            "recently_adopted": true,
            "prefers_people": false,
            "leash_aggression": false,
            "elderly_dog": false,
            "little_time_with_other_dogs": false,
            "much_experience_with_other_dogs": false,
            "aggressive": false,
            "owner_description": "Santos is a retired racing hound whom I just adopted.  He's still getting used to commands and obeying me, but he's very sweet and plays well with other dogs.  He's very energetic and needs similarly speedy dogs to play with.  If you live in the greater Springfield area, look for us out on the town!"
        },
        {
            "id": '7cb90576-b26c-4344-bb0b-915429e4fc2b',
            "owner_id": '51230acf-f502-4cd0-812b-e4dd59b04cb1',
            "name": "Laddie",
            "profile_img_url": "https://images.unsplash.com/photo-1524729429516-485db0307e59?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80",
            "age_years": 2,
            "age_months": 0,
            "sex": "male, neutered",
            "breed": "Border collie",
            "weight": 40,
            "energy": "Very energetic",
            "temperment": "Somewhat indifferent to most dogs",
            "obedience": "Very-well trained and always obedient.",
            "dislikes_puppies": true,
            "dislikes_men": false,
            "dislikes_women": false,
            "dislikes_children": false,
            "recently_adopted": false,
            "prefers_people": true,
            "leash_aggression": false,
            "elderly_dog": false,
            "little_time_with_other_dogs": true,
            "much_experience_with_other_dogs": false,
            "aggressive": false,
            "owner_description": "Laddie is brilliant and highly trained.  He is extremely loyal and very friendly towards people.  He does not, however, seem to enjoy playing with other dogs.  He is not aggressive: he simply ignores other dogs, especially puppies, which seem to annoy him a lot.  I just got a new dog, however, so I want him to learn to play with other dogs."
        },
        {
            "id": 'cb6e6549-faac-45ae-9170-b11c869cd239',
            "owner_id": 'fccf7cab-93e7-4b1b-ae26-a1f6e24f1b6d',
            "name": "Abner",
            "profile_img_url": "https://images.unsplash.com/photo-1529927066849-79b791a69825?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1049&q=80",
            "age_years": 7,
            "age_months": 0,
            "sex": "female, spayed",
            "breed": "pug",
            "weight": 15,
            "energy": "Not very...",
            "temperment": "Nervous around new people or dogs",
            "obedience": "Well trained in basic commands and generally obedient.",
            "dislikes_puppies": false,
            "dislikes_men": true,
            "dislikes_women": false,
            "dislikes_children": false,
            "recently_adopted": true,
            "prefers_people": false,
            "leash_aggression": true,
            "elderly_dog": false,
            "little_time_with_other_dogs": true,
            "much_experience_with_other_dogs": false,
            "aggressive": true,
            "owner_description": "Abner is a dog in recovery from an abusive past.  I just adopted her and so she is still learning how to live in a loving home.  She's very shy around new people, especially men, but I want to start introducting her to strangers very slowly.  She can be aggressive on the leash and around food, so I'm looking for a very patient dog to help her find her way."
        },
    ],
    "howls": [],
    "reviews": [],
}